import React from 'react'
export const metadata = {
  title: "Create Header",
  description: "Generated by create next app",
};
export default function About() {
  return (
    <div>About</div>
  )
}
