import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header.js";
import AppLoader from "@/components/AppLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="header-container sm:mx-3 md:mx-8 lg:mx-15 xl:mx-18">
          <AppLoader>
            <Header />

            <main id="main-tag">{children}</main>
          </AppLoader>
        </div>
      </body>
    </html>
  );
}
